# Generated by Django 5.1.7 on 2025-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_city_alter_edu_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
