# Generated by Django 5.1.7 on 2025-03-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_email_alter_achievements_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='core.customuser'),
        ),
    ]
