# Generated by Django 5.1.7 on 2025-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='profi',
            field=models.CharField(max_length=100),
        ),
    ]
